### ISSUE TITLE
is it possible to add a version with multiple controlnet?

### ISSUE THREAD

**Issue by sourceful-karlson** [fofr/cog-comfyui-xlabs-flux-controlnet#1]
i am asking as we can add multiple controlnet with canny as well as depth to have better result

**Comment by fofr** [comment]
Have you tried multi-controlnet in Comfy with these models and have you had good results?

**Comment by sourceful-karlson** [comment]
I am very new to this, is it possible if you can give me a few pointers on how to run this repo using comfy?

**Comment by sourceful-karlson** [comment]
![Screenshot 2024-08-28 at 14 39 20](https://github.com/user-attachments/assets/2fabcede-4151-45a4-9bed-57db0c6897b7)


got it, running the submodule

**Comment by fofr** [comment]
Essentially, I don't think these controlnet weights are good enough for multi yet

**Comment by sourceful-karlson** [comment]
we have done something similar for sdxl and have got good result, which is why I have asked. 

But we have some good result with the lora and canny

Will patiently wait for future iteration of this.

**Comment by sourceful-karlson** [comment]
thanks for looking into i am testing this with the web based comfy ui on fal and hopefully get the multi controlnet to work!
